eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.249.228:8761/eureka/
  instance:
    hostname: arfan

management:
  zipkin:
    tracing:
      endpoint: http://192.168.249.228:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1.0

spring:
  data:
    mongodb:
      host: http://192.168.249.228
      port: 27017
      database: ds_project
      
logging:
  file:
    name: C:\Users\user\Desktop\LLLoggg\logger.log    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
  product-service:
    endpoints:
      endpoint:
        uri: http://PRODUCT-SERVICE/product/products-by-cat-id  
